require 'spec_helper'
require 'active_record'
require_relative '../../lib/models/parking.rb'
require_relative '../../lib/config/establish_connection.rb'
require_relative '../../lib/models/slot.rb'
require_relative '../../lib/models/vehicle.rb'
require_relative '../helper_methods.rb'